import Head from "next/head";
import { useEffect, useState } from "react";
import { ethers } from "ethers";
export default function Home() {
  const [provider, setProvider] = useState({});
  const [wallet, setWallet] = useState({
    address: "0x00000000000000000000000000000000000000",
    balance: 0,
  });
  useEffect(() => {
    if (
      typeof window.ethereum !== "undefined" ||
      typeof window.web3 !== "undefined"
    ) {
      const provider = new ethers.providers.Web3Provider(window.ethereum);
      setProvider(provider);
    } else {
      console.log("No web3? You should consider trying MetaMask!");
    }
  }, []);
  const connectWallet = async () => {
    try {
      const [account] = await window.ethereum.request({
        method: "eth_requestAccounts",
      });
      const wallet = provider.getSigner(account);
      setWallet({
        address: account,
        balance: ethers.utils.formatEther(await wallet.getBalance()),
      });
      console.log(wallet);
    } catch (error) {
      console.log(error);
    }
  };
  const disconnectWallet = async () => {
    try {
      await window.ethereum.request({
        method: "eth_requestAccounts",
      });
      setWallet({
        address: "0x00000000000000000000000000000000000000",
        balance: 0,
      });
      console.log(wallet);
    } catch (error) {
      console.log(error);
    }
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        {wallet ? (
          <div>
            <p>
              Your wallet address is:
              <br />
              {wallet.address}
            </p>
            <p>
              Your wallet balance is:
              <br />
              {wallet.balance} ETH
            </p>
          </div>
        ) : null}
        <button onClick={connectWallet} className="mb-8">
          <div className="flex flex-row bg-[#F5841F] text-white">
            <p className="p-2">Connect to Metamask</p>
          </div>
        </button>
        <button onClick={disconnectWallet}>
          <div className="flex flex-row bg-[#48270b] text-white">
            <p className="p-2">Disconnect from Metamask</p>
          </div>
        </button>
      </main>
    </div>
  );
}